### ISSUE TITLE
Possible collab with raylib-hx

### ISSUE THREAD

**Issue by Akselmo** [rc-05/haxe-raylib#1]
Hey, could these bindings be pushed to https://github.com/foreignsasquatch/raylib-hx/ ?

This way we wouldn't need to have multiple libraries :D 

I mentioned your project here https://github.com/foreignsasquatch/raylib-hx/issues/26

**Comment by rc-05** [comment]
Sorry for not responding earlier: sure we can merge the two libraries into one.
